### PR TITLE
Add an example implementation of GeniePath model

### PR DESCRIPTION
**Pull request by shawnwang-tech**
This PR adds an example implementation of GeniePath model in <GeniePath: Graph Neural Networks with Adaptive Receptive Paths> (https://arxiv.org/abs/1802.00910)

GeniePathLazy Model Performance:
Epoch: 100, Loss: 0.0170, Acc: 0.9747 

Paper info:
GeniePath: Graph Neural Networks with Adaptive Receptive Paths. Ziqi Liu, Chaochao Chen, Longfei Li, Jun Zhou, Xiaolong Li, Le Song, Yuan Qi. AAAI, 2019.

### CODE REVIEW

**Comment by rusty1s** [comment]
Really cool. Thank you very much. Do you think we could outsource this as a generic model to `nn.models` or `nn.conv`?

**Comment by shawnwang-tech** [comment]
Of course you can! I love PyG!

**Comment by rusty1s** [comment]
Ok, I will read the paper and code in more detail and will merge afterwards.

**Comment by shawnwang-tech** [comment]
Thank you!

**Comment by rusty1s** [comment]
Thank you again :)

**Pull request merged**
