### PR TITLE
Added more autoencoder models. Need help debugging them and making them work with my + other's datasets.

### PR DESCRIPTION
**Pull request by jlevy44**
Thanks! I'll be here to help develop. Seems like some of your autoencoder test scripts need to be fixed as well.

### CODE REVIEW

**Comment by jlevy44** [comment]
Let's see if we can finish this PR soon :)

**Comment by rusty1s** [comment]
Thanks! Looks good! I will fix sone things and merge ASAP, e.g., you need to call BCEWithLogitsLoss when omitting the sigmoid.

**Comment by rusty1s** [comment]
Updated models in master. I will also add an example.

**Comment by rusty1s** [comment]
I think your implementation of adversarial autoencoders were wrong. You need two optimizers for adversarial optimization: One for the encoder, and one for the discriminator.

**Comment by jlevy44** [comment]
Ah thanks. I was going to mention that they had bugs and were not fully tested.

**Comment by jlevy44** [comment]
You’re implementation looks great though. Can’t wait to use

**Pull request merged**
