### PR TITLE
Create negative_sampling utils

### PR DESCRIPTION
**Pull request by dongkwan-kim**
- Caught errors in negative_sampling, negative_triangle_sampling
- Create a batch version of negative_sampling
- Put all three in one utils/negative_sampling module.
- Add tests.

### CODE REVIEW

**Comment by rusty1s** [comment]
Looks really good, will merge ASAP.

**Comment by rusty1s** [comment]
I think this PR is now ready for merge. I removed the `is_directed` flag because in PyG we implement undirected graphs by encoding both directions in `edge_index`. WDYT?

**Comment by dongkwan-kim** [comment]
> I think this PR is now ready for merge. I removed the `is_directed` flag because in PyG we implement undirected graphs by encoding both directions in `edge_index`. WDYT?

Oh, I see. Then, I am ok with that. Thank you for nice refactoring.

But, I found a mistake in line 29 of this commit (https://github.com/rusty1s/pytorch_geometric/pull/622/commits/6021aee3f3845627d8a817cb8b4784fa67bfc367#diff-ac3d66c32da6eab12a976416c535a12e). I think that edge_index.size(0) should be edge_index.size(1), since edge_index is a tensor the shape of which is [2, num_edges]. Could you look at this?

**Comment by rusty1s** [comment]
Yes, thank you!

**Comment by dongkwan-kim** [comment]
Hi, @rusty1s 

A few months ago, we agreed to remove `is_directed` for the input edge_index.
However, sometimes, we might need an output of undirected negative samples.

What do you think about adding `force_undirected` (bool, optional) to input attributes, like `dropout_adj`?

**Comment by rusty1s** [comment]
Yes, I think we can do this by only working on the upper triangle adjacency matrix.

**Comment by dongkwan-kim** [comment]
OK. I will send a pull request about this soon.

**Pull request merged**
