### PR TITLE
small bug fix for reddit.py

### PR DESCRIPTION
**Pull request by jzhou316**
The neighbor sampler only accepts torch.LongTensor instead of bool masks.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thank you! The NeighborSampler already supports bool tensors, see [here](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/sampler.py#L148). Does this not work for you?

**Comment by jzhou316** [comment]
Oh I just read through that line! It works. My bad. Thanks for the quick response, I think it's my version (1.3.1) was before the update.

By the way, is there any quick way to grab all the neighbors of a node instead of sampling, by using the current functions from torch_cluster?

**Comment by rusty1s** [comment]
Well, you can set the size to `1.0` to sample *all* neighbors.

**Comment by jzhou316** [comment]
Thanks!!

**Pull request closed without merging**
