### PR TITLE
add SEAL link prediction example

### PR DESCRIPTION
**Pull request by muhanzhang**
Hi, following the discussion in https://github.com/rusty1s/pytorch_geometric/issues/634, I added an example implementation of SEAL for link prediction, introduced by "Zhang, Muhan, and Yixin Chen. Link prediction based on graph neural networks. Advances in Neural Information Processing Systems. 2018." On Cora, it achieved 0.9332 +/- 0.0016 AUC, compared to the 0.9104 +/- 0.0036 AUC of GAE in "link_pred.py". Please let me know whether it can be added to PyG's examples or any additional tests/modifications need to be added.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thanks, this is super cool! I made a pass through the PR and made some changes. For example, the pre-processing now takes place inside the `SEALDataset`. Otherwise, I mostly cleaned it up a little bit.

Really cool to have an example of it, thank you very much!

**Comment by muhanzhang** [comment]
Cool! Thank you very much for cleaning!

**Comment by massawuyh** [comment]
Hi, I read through the paper and I notice we can pass node embedding and node features, can you advise in the example which code is for adding node embedding and node features? Thanks a lot

**Comment by muhanzhang** [comment]
> Hi, I read through the paper and I notice we can pass node embedding and node features, can you advise in the example which code is for adding node embedding and node features? Thanks a lot

Change this [line](https://github.com/rusty1s/pytorch_geometric/blob/a21edf1417b8d3b24edc31515ca4eee5e494ce1a/examples/seal_link_pred.py#L68) to something like:

    z = F.one_hot(data.z, self.__max_z__ + 1).to(torch.float)
    data.x = torch.cat([z, data.x], 1)

in order to include node attribute features. You may also train and include node embeddings there. But they do not often improve the performance over using purely subgraph structures.

**Comment by massawuyh** [comment]
Thanks! I will try!

**Comment by massawuyh** [comment]
Hi, muhanzhang, I am wondering if I can change GCN to SageConv? 
Have you tried using SageConv?Will it improve performance?

**Comment by muhanzhang** [comment]
> Hi, muhanzhang, I am wondering if I can change GCN to SageConv?
> Have you tried using SageConv?Will it improve performance?

No, I haven't. The GNN architecture in SEAL is flexible. I have tried GIN but saw worse performance. You may have a try of SageConv.

**Comment by massawuyh** [comment]
> > Hi, muhanzhang, I am wondering if I can change GCN to SageConv?
> > Have you tried using SageConv?Will it improve performance?
> 
> No, I haven't. The GNN architecture in SEAL is flexible. I have tried GIN but saw worse performance. You may have a try of SageConv.

Thank you !!

**Comment by massawuyh** [comment]
> > Hi, I read through the paper and I notice we can pass node embedding and node features, can you advise in the example which code is for adding node embedding and node features? Thanks a lot
> 
> Change this [line](https://github.com/rusty1s/pytorch_geometric/blob/a21edf1417b8d3b24edc31515ca4eee5e494ce1a/examples/seal_link_pred.py#L68) to something like:
> 
> ```
> z = F.one_hot(data.z, self.__max_z__ + 1).to(torch.float)
> data.x = torch.cat([z, data.x], 1)
> ```
> 
> in order to include node attribute features. You may also train and include node embeddings there. But they do not often improve the performance over using purely subgraph structures.


I am lit bit confused about node embedding, in the example, you use cora dataset, so the node already has node embedding right? 2708*1433?

**Comment by muhanzhang** [comment]
No, the 2708 * 1433 are node attribute features. They are bag of words features describing the documents (nodes) in Cora. Node embedding needs running network embedding algorithms (such as DeepWalk, node2vec, LINE, etc.) to get.

**Comment by massawuyh** [comment]
> No, the 2708 * 1433 are node attribute features. They are bag of words features describing the documents (nodes) in Cora. Node embedding needs running network embedding algorithms (such as DeepWalk, node2vec, LINE, etc.) to get.

Got it, Thanks!

**Comment by MLAlex1** [comment]
Hi @muhanzhang , thanks for this fantastic example. 
I noticed that in the dataset every pair of nodes has an undirected edge [(0,1), (1,0), (2,1), (1,2)] etc.. which results in a duplication of the subgraphs in the data loaders, as computing subgraphs for [1,2] or [2,1] gives the same output. For a bigger dataset this might lead to memory problems when saving the dataset with torch.save().
Now i am wondering if i am missing something or it is fine to remove those duplicates?
Thanks in advance!

**Comment by muhanzhang** [comment]
@MLAlex1 Hi! Your point makes sense. If the training data contain edges of both directions, then the current implementation does not remove duplicates and samples subgraphs for both. I believe you can remove the duplicates at the stage of sampling training edges, like commenting out this [line](https://github.com/rusty1s/pytorch_geometric/blob/22bef0517cbaf51b14428fddb2be4a49dd924609/torch_geometric/utils/train_test_split_edges.py#L47). We don't need duplicate edges for undirected graphs.

**Comment by MLAlex1** [comment]
Thanks, that's exactly what I did!

**Pull request merged**
