### PR TITLE
Extending Gnnexplainer for graph classification.

### PR DESCRIPTION
**Pull request by wsad1**
#1374
Updated Gnnexplainer to support graph classification. Following are the key updates.

1. Added `explain_graph` which should be called for graph classification. This has lots of code similar to `explain_node`. Another solution would be to have a `explain` function that handles both graph or node explanation, however that would mean `explain_node` would have to be retired/depreciated, let me know if you feel that's a better solution.
2. In `visualize_subgraph` setting `node_idx` to -1 implies a graph classification task.

Further i'll add an example for this in a day or two. But feel free to review the code.

### CODE REVIEW

**Comment by rusty1s** [comment]
This is super awesome. Thanks a lot! I already fixed the failing `PairNorm` test in master.

**Comment by Luoyunsong** [comment]
Hello , I have got an erro "type object 'GNNExplainer' has no attribute 'explain_graph'"...Is that a wrong version for me?

**Comment by Luoyunsong** [comment]
Thanks a lot!

**Comment by Luoyunsong** [comment]
My code:
---------------------------------------------------------------------------
x1, edge_index1 = testing_dataset[1].x, testing_dataset[1].edge_index
explainer = GNNExplainer(model, epochs=200)
node_idx = -1
graph_feat_mask, edge_mask = explainer.explain_graph( x1, edge_index1)
ax, G = explainer.visualize_subgraph(node_idx,edge_index1, edge_mask, y=testing_dataset[1].y)
plt.show()
---------------------------------------------------------------------------

And the erro:
---------------------------------------------------------------------------
Explain graph: 100%|██████████| 200/200 [00:00<00:00, 203.63it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-37-b2b225a43ce0> in <module>()
      2 node_idx = -1
      3 graph_feat_mask, edge_mask = explainer.explain_graph( x1, edge_index1)
----> 4 ax, G = explainer.visualize_subgraph(node_idx,edge_index1, edge_mask, y=testing_dataset[1].y)
      5 plt.show()

/usr/local/lib/python3.7/dist-packages/torch_geometric/nn/models/gnn_explainer.py in visualize_subgraph(self, node_idx, edge_index, edge_mask, y, threshold, **kwargs)
    311                             device=edge_index.device)
    312         else:
--> 313             y = y[subset].to(torch.float) / y.max().item()
    314 
    315         data = Data(edge_index=edge_index, att=edge_mask, y=y,

IndexError: too many indices for tensor of dimension 0


The shape of my edge_index0 is "torch.Size([2, 450])",I really dont know how to set these parameters

**Comment by wsad1** [comment]
@Luoyunsong , could you please share the shape of `testing_dataset[1].y`, `testing_dataset[1].x` and `testing_dataset[1].edge_index`. This should help me debug this better.

**Comment by Luoyunsong** [comment]
I was doing a brain network classfication.
The shape of `testing_dataset[1].y` is `torch.Size([])`,which is the label of a brain network graph,'0' and '1'.
The shape of `testing_dataset[1].x` is `torch.Size([90, 90])`.
The `testing_dataset[1].edge_index.max()` is `tensor(89)`,and its shape is `torch.Size([])`
Thanks for your help

**Comment by wsad1** [comment]
@Luoyunsong, thanks for bringing this up. This is a bug, i'll create a PR to fix this asap. In the meanwhile could to try setting `y` to `None` to get around the bug `explainer.visualize_subgraph(node_idx,edge_index1, edge_mask, y=None)`.

**Comment by Luoyunsong** [comment]
Thanks for your help and its a perfect work

**Comment by wsad1** [comment]
@panisson are you referring to this line in the loss function.
'''
loss = -log_logits[ node_idx, pred_label[node_idx]] if node_idx == -1 else -log_logits[                
                                                                                                                               0, pred_label[0]]
'''

**Comment by rusty1s** [comment]
Yes, this seems to be indeed a crucial bug. We might need to hot-fix the new release.

**Comment by wsad1** [comment]
Thanks @panisson for catching this. @rusty1s  fixed it 35f5ac319ee864ee6a3ee9f6ee6619d34cc5d388.

**Comment by hanao2** [comment]
Hello,

Thanks for the implementation of graph-level explainer. Regarding my explain_graph output, neither the node_feat_mask nor the edge_mask have a sum equal to one. How should we go about this? Thanks!

**Comment by htlee6** [comment]
Hi all! Is this feature still available in version `2.3.0`? Thanks

**Comment by rusty1s** [comment]
Yes, graph classification within `GNNExplainer` is fully supported.

**Comment by Paul1086** [comment]
Hi, I am a beginner at GNN. Just have a question, Does the node_feat_mask of explain_graph directly give the node feature importance for the entire graph classification? Or, do we need to follow other steps to find the feature importance after obtaining node_feat_mask?

**Comment by rusty1s** [comment]
You should be able to directly use it, and it will contain the feature importance of the entire graph.

**Comment by sumone-compbio** [comment]
Hi, is there any tutorial or example code available for explain_graph? Thank you.

**Comment by rusty1s** [comment]
No example yet, but hopefully the test case gets you going: https://github.com/pyg-team/pytorch_geometric/blob/master/test/explain/algorithm/test_gnn_explainer.py#L80

**Comment by sumone-compbio** [comment]
@rusty1s thanks a lot. I'm new to XAI methods. Can you please tell me what would be the input here? The training set on which the model (e.g. GCNConv) is trained (to see how the model can differentiate between 2 classes for a binary classification problem) or the held-out test set?

**Comment by rusty1s** [comment]
It depends on what explanations you want to receive. In general, I think it is more common to run explanations on hold out data. You can then find common substructures by looking at the edge attribution.

**Comment by sumone-compbio** [comment]
@rusty1s thank you I'm still working on it. I got the error: 'GNNExplainer' object has no attribute 'explain_graph'. Even though I installed PyG from the master link above. Am I missing something?

**Comment by rusty1s** [comment]
Are you using `GNNExplainer` from `torch_geometric.explain`?

**Comment by sumone-compbio** [comment]
@rusty1s yes. This is the code I am running:
`from torch_geometric.explain import GNNExplainer
x0, edge_index0 = test_dataset[0].x, test_dataset[0].edge_index
explainer = GNNExplainer(model=model, epochs=400, lr=0.0001)
graph_feat_mask, edge_mask = explainer.explain_graph( x1, edge_index1)`

**Following is the error:** 
AttributeError                            Traceback (most recent call last)
Cell In[40], [line 2](vscode-notebook-cell:?execution_count=40&line=2)
      [1](vscode-notebook-cell:?execution_count=40&line=1) node_idx = -1
----> [2](vscode-notebook-cell:?execution_count=40&line=2) graph_feat_mask, edge_mask = explainer.explain_graph( x1, edge_index1)

File [~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1688](https://file+.vscode-resource.vscode-cdn.net/home/sumit/Downloads/transfer/BBB_new/~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1688), in Module.__getattr__(self, name)
   [1686](https://file+.vscode-resource.vscode-cdn.net/home/sumit/Downloads/transfer/BBB_new/~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1686)     if name in modules:
   [1687](https://file+.vscode-resource.vscode-cdn.net/home/sumit/Downloads/transfer/BBB_new/~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1687)         return modules[name]
-> [1688](https://file+.vscode-resource.vscode-cdn.net/home/sumit/Downloads/transfer/BBB_new/~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1688) raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'GNNExplainer' object has no attribute 'explain_graph'

The model I am using is GraphConv from PyG. I couldn't fix this error.

**Comment by rusty1s** [comment]
That would be an incorrect use of `GNNExplainer`. You need to wrap it inside an `Explainer` module (take a look at our examples on how to do this).

**Comment by sumone-compbio** [comment]
sorry, I couldn't understand by looking at the example. 
I was referring to this:
test/nn/models/test_gnn_explainer.py in https://github.com/pyg-team/pytorch_geometric/pull/2597/commits/751200466aa3c0affa342f92885d8f6c823823d0.

For other code in https://github.com/pyg-team/pytorch_geometric/blob/master/examples/explain/gnn_explainer.py (I assume for node classification) I didn't understand what parameters are different for graph-level classification.

**Comment by rusty1s** [comment]
Here is how you would use `GNNExplainer` now:
```python
explainer = Explainer(
    model=model,
    algorithm=GNNExplainer(epochs=200),
    explanation_type='model',
    node_mask_type='attributes',
    edge_mask_type='object',
    model_config=dict(
        mode='multiclass_classification',
        task_level='graph',
        return_type='log_probs',
    ),
)
```

**Comment by rusty1s** [comment]
If `batch_index` is an expected argument of the model, you also need to add it to the `explainer`:
```python
explanation = explainer(x=x0, edge_index=edge_index0, batch_index=..., target=None)
```

**Comment by sumone-compbio** [comment]
@rusty1s thank you so much it worked finally. However, it generates a slightly different graph every time I re-run the explanation.visualize_graph function. Could you let me know what this is? Also, instead of a directed graph is there a way to get an undirected graph so that later I can map the nodes to atoms to visualize molecules with functional groups or substructures important to the prediction? Thanks a ton, once again <3.

**Comment by rusty1s** [comment]
You would interpret it as case 2.

**Comment by sumone-compbio** [comment]
@rusty1s thank you, I was in doubt because a lot of my graph '0' has low edge_masks. Case 2 makes sense as the explainer also works on multiclass classification.

**Comment by sumone-compbio** [comment]
Dear @rusty1s, I have one more doubt, please. I did not provide any threshold to edge_masks or node_masks in the explainer but still, the explainer can provide the subgraph and I get evaluation metric results as well e.g. unfaithfulness, fidelity score, etc. How the subgraph is generated in my case?

**Comment by rusty1s** [comment]
In this case, node and edge importance is just given as a continuous value between 0 and 1.

**Pull request merged**
