### PR TITLE
Add GDC

### PR DESCRIPTION
**Pull request by klicperajo**
This PR implements the full pipeline used by Graph Diffusion Convolution (GDC) from "Diffusion Improves Graph Learning" (NeurIPS 2019) as a preprocessing step (data transformation).

GDC is monolithically implemented in a single class. Not sure if it would be smarter to split up the separate steps and then just call them in a wrapping GDC function. But I think this is a good (and complete) start.

I've also added a fast and scalable implementation of PPR for this. This implementation requires Numba, so I've added Numba to the required packages. I'm open to better ways of handling this.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thank you very much! This already looks really good. I will try to merge this ASAP.

**Comment by klicperajo** [comment]
Great! By the way, is there an easy way provided by PyG to obtain the largest connected component (LCC) of a graph? That would be very useful.

**Comment by klicperajo** [comment]
Should I just extend `gcn.py` with GDC or write an additional file, based on `gcn.py`?

**Comment by rusty1s** [comment]
I believe the easiest way is to convert your graph to `networkx`. We do not have our own implementation for this.

I think adding an argument to `gcn.py` with `argparse` should be sufficient, but this is up to you :)

**Comment by klicperajo** [comment]
Done. I've also fixed the GCN normalization while I was at it.

**Comment by klicperajo** [comment]
Should the documentation or something point to where this example is?

**Comment by rusty1s** [comment]
Sure, we could add a link to it to let users know about it :)

**Comment by klicperajo** [comment]
Not sure if this will work, but I've added a link.

**Comment by rusty1s** [comment]
Works perfectly! i just fixed some linting problems. Thank you once again!

**Comment by Oliver-0423** [comment]
is there an easy way provided by PyG to obtain the largest connected component (LCC) of a graph now?

**Pull request merged**
