### PR TITLE
Added option to directly specify k for topk_pool and some pooling methods.

### PR DESCRIPTION
**Pull request by mrmotallebi**
Small modification to directly specify the number of nodes for Top-K Pooling. Instead of looking at the ratio of pooling, directly specify the number of nodes to keep, overriding the ratio.
Put K as the last parameter in order to not break other functions.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thank you very much! This looks good :)

One minor thing: Instead of adding an additional argument `k`, how about we allow `ratio` to represent both float values (in interval [0, 1]) and integer values.

**Comment by mrmotallebi** [comment]
That actually sounds like a good idea! My only concern would be that the term "ratio" would not be easily understandable as the number of nodes to maintain (k), but I guess the current usecase (ratio of total number of nodes) is more common and if we add the explanation for the other one in the docs, it should be good.
I'll update the code.

**Comment by mrmotallebi** [comment]
Sorry for the delay. Updated the code and docs, and added the tests. Please have a look.

**Comment by rusty1s** [comment]
Thank you very much! I've made a pass and also fixed the `k > num_nodes` error.

**Pull request merged**
