### PR TITLE
Fix a bug in gcn_norm

### PR DESCRIPTION
**Pull request by jeffhj**

### CODE REVIEW

**Comment by rusty1s** [comment]
Can you clarify? Why is that a bug?

**Comment by jeffhj** [comment]
> Can you clarify? Why is that a bug?

Hi @rusty1s, from the implementation of SparseTensor on https://github.com/rusty1s/pytorch_sparse/blob/master/torch_sparse/tensor.py, I found that fill_value_() is an in-place operation, but fill_value() not.

**Comment by rusty1s** [comment]
That's true. But I don't think we want to modify the `SparseTensor` in-place, since that would result in unexpected behaviour outside this operator.

**Comment by rusty1s** [comment]
Oh, but it doesn't get assigned to a new tensor. You're right. Thats a bug!

**Comment by jeffhj** [comment]
> Oh, but it doesn't get assigned to a new tensor. You're right. Thats a bug!

Yes, if we don't use in-place operation, we should use `adj_t = adj_t.fill_value(1., dtype=dtype)` instead.

**Comment by rusty1s** [comment]
Thanks :)

**Pull request merged**
