### PR TITLE
Added the FEATHER datasets

### PR DESCRIPTION
**Pull request by benedekrozemberczki**
Added two node classification datasets from this paper:

Characteristic Functions on Graphs: Birds of a Feather, from Statistical Descriptors to Parametric Models

https://arxiv.org/abs/2005.07959

The datasets are also hosted on SNAP.

### CODE REVIEW

**Comment by benedekrozemberczki** [comment]
Besides the FEATHER datasets I added the following modifications:

1. The Geom-GCN people dropped certain node features and truncated the target variable for the Wiki dataset which is not in the original paper.
2. One of the Wiki datasets was left out for no reason.
3. Added the datasets from the GEMSEC paper - these are widely used for multi-label multi-class node classification

**Comment by rusty1s** [comment]
Thank you very much! You are that the Wiki dataset used in Geom-GCN differs from the original dataset. I was not aware of this. One concern that I have is backward compatibility/supporting the Geom-GCN pre-processing strategy as well.

Do you think it is useful to add some `geom_gcn_preprocess` argument that converts the original dataset into the GeomGCN variant (e.g., adding splits and casting the dataset to node classification task)?

**Comment by benedekrozemberczki** [comment]
Hi there,

Yes, I can add a pre-processing step and add the classification targets to the NumPy pickle and load the appropriate target for the users.

Bests,

Benedek

**Comment by benedekrozemberczki** [comment]
1. Reuploaded the dataset with the labels and masks on graphmining.ai.
2. Created a set of masks (10) and classification labels for the third dataset.
2. Added a preprocessing parameter for the loader - now it supports the masks and both types of targets (classification/regression).

**Comment by rusty1s** [comment]
Thank you very much for supporting this :) This is great!

**Pull request merged**
