### PR TITLE
Add `ratio` and `JK` as args to kernels

### PR DESCRIPTION
**Pull request by ekagra-ranjan**
This PR introduces `ratio` and `JK ` as args to various models in kernels.

### CODE REVIEW

**Comment by rusty1s** [comment]
Thank you. I guess the following Linear layer after the JK layer needs adjustment to, whether one uses the concat method or not.

**Comment by ekagra-ranjan** [comment]
I am on it!

**Comment by ekagra-ranjan** [comment]
@rusty1s  Done! Please have a look at it.

**Comment by rusty1s** [comment]
Hi and thank you, I'm actually not that big of a fan of allowing different JK modes for hierarchical models because we are already on the graph-level. For modes `max` and `lstm`, their big strengths are their node-adaptive aggregation, something which is already lost after global pooling. We should just use `cat` and shouldn't allow any modifications here. Other than that, it looks good to me :)

**Comment by ekagra-ranjan** [comment]
Cool! When you asked me to make changes on linear layers after JK I though that `max` and `lstm` would be meaningful. But I guess you are right about their strengths in node-adaptive aggregations which might not make sense after global pooling. I will make the changes you suggested.

**Comment by ekagra-ranjan** [comment]
Can we leave the `max` and `lstm` in the `Block` class in Diffpool or should I remove that too?

**Comment by rusty1s** [comment]
You can leave it there.

**Comment by ekagra-ranjan** [comment]
Done.

**Comment by rusty1s** [comment]
Thank you :)

**Pull request merged**
