### PR TITLE
Shapenet version that loads all categories together

### PR DESCRIPTION
**Pull request by GrumpyZhou**
Hi @rusty1s ,

This dataset relabels the label of each category in preprocess step, so that one can use it to train on all categories together and from my experiments it also works with the segmentation script that i uploaded in my last pull request.

### CODE REVIEW

**Comment by rusty1s** [comment]
Hi and thank you. Just wondering if this is common practice to train this dataset all at once?

**Comment by GrumpyZhou** [comment]
Hi, 

Yes i think it is the common practice. You can look at [pointnet++ original implementation](https://github.com/charlesq34/pointnet2/blob/master/part_seg/part_dataset_all_normal.py).
Simply by looking the code, first there's no where you can define the category for training, secondly, looking at line 74-75 it is obvious they need to remap the labels. Finally, it also doesn't make much sense to evaluate a model on a single category... like we never train classifier for only 1 class.

**Comment by rusty1s** [comment]
I unified the `ShapeNet` and `ShapeNetAll` datasets. Users can now pass in a list of categories (or `None` if they want to load all categories together).

**Comment by GrumpyZhou** [comment]
Cool, thanks!

**Pull request merged**
