### PR TITLE
Lazy loading for `datasets` and `nn.models`

### PR DESCRIPTION
**Pull request by Linux-cpp-lisp**
See discussion in #2189 .

This PR uses the `LazyLoader` class from TensorFlow to lazy-load `torch_geometric.datasets` and `torch_geometric.nn.models`.

The file from TensorFlow is under an Apache 2.0 license, so it should be fine to include in an MIT license project? See:

- https://softwareengineering.stackexchange.com/questions/297217/using-code-under-apache-2-0-license-in-my-program-using-mit-license
- https://opensource.stackexchange.com/questions/8135/can-i-use-mit-isc-apache-2-0-in-a-project-licensed-as-mit-or-apache-2-0
- https://law.stackexchange.com/questions/6081/can-i-bundle-mit-licensed-components-in-a-apache-2-0-licensed-project

### CODE REVIEW

**Comment by Linux-cpp-lisp** [comment]
The last commit is needed to lazy load all of `nn` instead of `nn.models`. Unfortunately, because `torch_geometric/nn/__init__.py` had 
```
from .models import *
```
there doesn't seem to be any way to lazy load those individual classes. 

This lazy loading setup (from TensorFlow) only supports modules. I tried to use `importlib.utils.LazyLoader` from the stdlib, but was unable to get it to work without circular import errors.

**Comment by rusty1s** [comment]
I further polished and achieved faster loading by fixing some imports in `torch_geometric.transforms` which directly imported from `torch_geometric.nn`.

**Comment by Linux-cpp-lisp** [comment]
Looks good, thanks @rusty1s . I'm not sure why the CI tests are failing, though.

**Comment by rusty1s** [comment]
CI fails because of https://github.com/pytorch/vision/issues/3504, which is independent of this PR.

**Pull request merged**
