### PR TITLE
measure for homophily

### PR DESCRIPTION
**Pull request by ldv1**
This is a measure of homophily as proposed in the paper [Geom-GCN: Geometric Graph Convolutional Networks](https://arxiv.org/abs/2002.05287).

### CODE REVIEW

**Comment by rusty1s** [comment]
Thank you. The existing implementation corresponds to the definition in [Beyond Homophily in Graph Neural Networks: Current Limitations and Effective Designs](https://arxiv.org/abs/2006.11468). Can you explain the differences to your proposed implementation?

**Comment by ldv1** [comment]
I observed that `homophily_ratio` and `homophily` do not give the exact same answer. For some very small graphs (e.g. synthetic ones), answers can be radically different, for others (like the ones from the homophily dataset), both provide answers that are very close.
I cannot tell the differences. One is sure: Some authors use this definition of homophily and it would be nice to have it. Furthermore, this definition is really intuitive. At least for me. And my code is documented.

**Comment by ldv1** [comment]
1/ There is now a single interface `homophily` to compute both kinds of homophily.
2/ I documented the homophily ratio.

**Comment by rusty1s** [comment]
Awesome :) Really appreciate your contributions!

**Comment by ldv1** [comment]
In the "edge" formula, the denominator must be \vert \mathcal{E} \vert instead of \vert \mathcal{V} \vert.
That's a mistake of mine, sorry.

**Comment by rusty1s** [comment]
You are right. Fixed it.

**Pull request merged**
