### PR TITLE
Support for concatenating along a new batch dimension

### PR DESCRIPTION
**Pull request by Linux-cpp-lisp**
Adds the first feature from issue #2030.

TODO:
- [x] Support for a `__cat_dim__` of `None` in `Batch.from_data_list`
- [x]  Support for the same in `InMemoryDataset`
- [x] Update documentation

### CODE REVIEW

**Comment by rusty1s** [comment]
This looks quite good to me. As far as I can see, you are simply unsqueezing the tensor in the first dimension in case `__cat_dim__ == 0`, which is quite elegant.

**Comment by Linux-cpp-lisp** [comment]
Thanks @rusty1s! This should be ready for review and merge now; the full test suite passes for me locally.

**Comment by Linux-cpp-lisp** [comment]
@rusty1s : wanted to check in and find out if this is still a feature you're planning to merge — no hurry, just curious for design decisions in our code. Thanks!

**Comment by rusty1s** [comment]
I plan to merge in the next week. Currently busy with an ICML submission, sorry for the delay!

**Comment by Linux-cpp-lisp** [comment]
No worries, just wanted to know — thanks and good luck with your submission!

**Comment by rusty1s** [comment]
Thanks a lot :)

**Comment by Linux-cpp-lisp** [comment]
Of course, thank you for all your work on torch_geometric!

**Pull request merged**
