### PR TITLE
Add Self Attention Graph Pooling

### PR DESCRIPTION
**Pull request by ekagra-ranjan**
This PR adds SAGPool from the paper "[Self-Attention Graph Pooling](https://arxiv.org/abs/1904.08082)". 

Result on MUTAG
```
MUTAG - SAGPool                                                                                                           
Val Loss: 0.5361, Test Accuracy: 0.722 _ 0.076, Duration: 3.016                                                           
Val Loss: 0.5061, Test Accuracy: 0.748 _ 0.068, Duration: 2.511                                                           
Val Loss: 0.4992, Test Accuracy: 0.738 _ 0.051, Duration: 2.638                                                           
Val Loss: 0.4851, Test Accuracy: 0.748 _ 0.086, Duration: 2.456                                                           
Val Loss: 0.5173, Test Accuracy: 0.715 _ 0.086, Duration: 4.845                                                           
Val Loss: 0.5092, Test Accuracy: 0.727 _ 0.079, Duration: 4.637                                                           
Val Loss: 0.4965, Test Accuracy: 0.738 _ 0.079, Duration: 4.838                                                           
Val Loss: 0.4779, Test Accuracy: 0.749 _ 0.059, Duration: 4.968                                                           
Val Loss: 0.4509, Test Accuracy: 0.724 _ 0.091, Duration: 5.725                                                           
Val Loss: 0.4201, Test Accuracy: 0.813 _ 0.092, Duration: 5.872                                                           
Val Loss: 0.3833, Test Accuracy: 0.754 _ 0.072, Duration: 5.683                                                           
Val Loss: 0.3883, Test Accuracy: 0.786 _ 0.100, Duration: 6.115                                                           
Val Loss: 0.4571, Test Accuracy: 0.722 _ 0.109, Duration: 8.489                                                           
Val Loss: 0.3689, Test Accuracy: 0.776 _ 0.079, Duration: 8.242                                                           
Val Loss: 0.3615, Test Accuracy: 0.786 _ 0.066, Duration: 8.277                                                           
Val Loss: 0.4386, Test Accuracy: 0.782 _ 0.069, Duration: 8.289                                                           
Val Loss: 0.4476, Test Accuracy: 0.707 _ 0.084, Duration: 8.301                                                           
Val Loss: 0.3985, Test Accuracy: 0.749 _ 0.061, Duration: 9.018                                                           
Val Loss: 0.3903, Test Accuracy: 0.768 _ 0.109, Duration: 8.487                                                           
Val Loss: 0.4535, Test Accuracy: 0.776 _ 0.085, Duration: 9.096    
Best result - 0.786 _ 0.066      
```

### CODE REVIEW

**Comment by rusty1s** [comment]
Thank you. As far as I see, we should reuse the helper functions from `topk.py`, shouldn't we?

**Comment by ekagra-ranjan** [comment]
Yes, we should definitely. I made the changes. Please have a look at them.

**Comment by ekagra-ranjan** [comment]
Should we make a separate helper file (eg: helper.py) for pooling operations in the pool folder?

**Comment by rusty1s** [comment]
Thank you. I guess the helper files can stay there, as they are closely related to topk pooling. I will have a closer look by tomorrow and will merge ASAP. Thanks again.

**Pull request merged**
